# Python Data Types

## (A) Simple Data Types - Hold only a single value

* float - real numbers
* int - interger numbers
* str - string (text)
* bool - True, False

## (B) Compund Data types - Hold more than a single value

* List
* Dictionaries
* Tuples

## List

* Used to name a collection of values
* It can contain any types of values
* It can contain different data types

In [11]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
list = [hall, kit, liv, bed, bath]

# Print areas
print(list)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [12]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [13]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


In [19]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


In [20]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


In [21]:
# The start index will be included, while the end index is not.
# my_list[start:end]

# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs (first 6 elements)
downstairs = areas[:6]

# Use slicing to create upstairs (last 4 elements)
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs, upstairs)

In [32]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

In [38]:
# Creating a copy of a list by list(x) or x[:]
# Otherwise changes made in the copied list will reflect in the original list as both list reference the same address in the backend

# Create list areas
areas1 = [11.25, 18.0, 20.0, 10.75, 9.50]
areas2 = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy1 = areas1
areas_copy2 = areas2[:]

# Change areas_copy
areas_copy1[0] = 5.0
areas_copy2[0] = 5.0

# Print areas
print(areas1, areas2)

[5.0, 18.0, 20.0, 10.75, 9.5] [11.25, 18.0, 20.0, 10.75, 9.5]


In [39]:
del(areas1[0])
print(areas1)

[18.0, 20.0, 10.75, 9.5]


## Functions and Methods

Function can be applied to any Python data type Ex: some_function(python_object)

A method is specific to each Python data type Ex: python_object.some_method()

In [14]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place, place_up)

# Print out the number of o's in place
print(place.count("o"))

poolhouse POOLHOUSE
3


In [15]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))


2
1


In [17]:
## Some of the string methods will change the list when they're called upon

# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)


# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

print(areas)
# Print out areas

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


## Packages

In [23]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*(r**2)

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [24]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


## Numpy

* Numeric Python
* Alternative to Python List is Numpy Array (Ex: You can't do list1/list2, you need to iterate over each element and then perform a division operator which is very costly. Numpy Array solves this issue)
* Calculation over entire arrays
* Easy and fast

In [6]:
# Numpy Arrays only contain a single data type
# Numpy Array is a new compound data type
# This means it comes with its own methods
# Indexing for numpy arrays is pretty similar to lists. Numpy Array can also use boolean to index which lists cannot.

In [15]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))
np_baseball

<class 'numpy.ndarray'>


array([180, 215, 210, 210, 188, 176, 209, 200])

In [17]:
# Import numpy
import numpy as np

height_in = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in*0.0254

# Print np_height_m
print(np_height_m)

[180 215 210 210 188 176 209 200]
[4.572  5.461  5.334  5.334  4.7752 4.4704 5.3086 5.08  ]


In [25]:
## Subsetting Numpy Array with boolean

# Import numpy
import numpy as np

height_in = [180, 215, 210, 210, 188, 176, 209, 200]
weight_lb = [18, 25, 21, 21, 18, 17, 20, 20]

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = (np_weight_kg / np_height_m ** 2)*100

# Create the light array
light = bmi < 35

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False  True  True False False  True False]
[33.47947648 33.47947648 32.19106734]


In [28]:
# In numpy.ndarray, numpy denotes that the array comes from the numpy package
# nd means n dimensional. This is because it is possible to create 1d, 2d.......n dimensional arrays
# 1d refers to only 1 axis, 2d refers to 2 axis. So 2d array can have 100 rows and 3 columns but it can be indexed using [row, column] hence a 2d array
type(np_weight_lb)

numpy.ndarray

In [30]:
# numpy 2d array can be thought of 2 lists in 1 list
# np.array(list1).shape => here shape is an attribute and not a method. Method has round brackets.

# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
print(np_baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
<class 'numpy.ndarray'>
(4, 2)


In [32]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [33]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 4th row of np_baseball
print(np_baseball[3,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 2nd player
print(np_baseball[1,0])

[188.   75.2]
215.0


In [34]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

198.25
199.0


In [35]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]
